-- CREATE SCHEMA no7;
-- --創建會員表格-------------------------------------------------
CREATE TABLE `MEMBER` (
 `MEMBER_ID` INT NOT NULL AUTO_INCREMENT,
 `MEMBER_NUMBER_OF_VIOLATIONS` INT DEFAULT 0,
 `MEMBER_NAME` VARCHAR(20) NOT NULL,
 `MEMBER_MAIL` VARCHAR(200) NOT NULL,
 `MEMBER_PASSWORD` VARCHAR(10) NOT NULL DEFAULT 'givegym123',
 `MEMBER_PHONE_NUMBER` VARCHAR(20) NOT NULL,
 `MEMBER_ADDRESS_REGION` VARCHAR(20) NOT NULL,
 `MEMBER_ADDRESS_DISTRICT` VARCHAR(20) NOT NULL,
 `MEMBER_ADDRESS_DETAIL` VARCHAR(200) NOT NULL,
 `MEMBER_BIRTHYEAR`  VARCHAR(20) NOT NULL,
 `MEMBER_BIRTHMONTH`  VARCHAR(20) NOT NULL,
 `MEMBER_BIRTHDAY` VARCHAR(20) NOT NULL,
 `MEMBER_STATE` BOOLEAN DEFAULT TRUE,
 PRIMARY KEY (`MEMBER_ID`)
);
-- --創建教練表格-------------------------------------------------
CREATE TABLE `COACH` (
`COACH_ID` INT NOT NULL AUTO_INCREMENT,
`COACH_NAME` VARCHAR(10) NOT NULL,
`COACH_DETAIL` VARCHAR(5000) NOT NULL,
`COACH_PIC` LONGBLOB,
`COACH_GENDER` CHAR(1) NOT NULL,
PRIMARY KEY (`COACH_ID`)
);
CREATE TABLE `SKILL` (
`SKILL_ID` INT NOT NULL AUTO_INCREMENT,
`SKILL_NAME` VARCHAR(20) NOT NULL,
PRIMARY KEY (`SKILL_ID`)
);
CREATE TABLE `COACHSKILL` (
`COACHSKILL_ID` INT NOT NULL AUTO_INCREMENT,
`COACH_ID` INT NOT NULL,
`SKILL_ID` INT NOT NULL,
PRIMARY KEY (`COACHSKILL_ID`),
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`),
FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`SKILL_ID`)
);
CREATE TABLE `PROCLASS` (
`PROCLASS_ID` INT NOT NULL AUTO_INCREMENT,
`SKILL_ID` INT NOT NULL,
`PROCLASS_NAME` VARCHAR(20) NOT NULL,
PRIMARY KEY (`PROCLASS_ID`),
FOREIGN KEY (`SKILL_ID`) REFERENCES `SKILL` (`SKILL_ID`)
);
CREATE TABLE `PROCLASSORDER` (
`PROCLASSORDER_ID` INT NOT NULL AUTO_INCREMENT,
`PROCLASS_ID` INT NOT NULL,
`MEMBER_ID` INT NOT NULL,
`PROCLASS_ATTEND` BOOLEAN,
`PROCLASS_TIME` CHAR(1),
`PROCLASS_DATE` DATE NOT NULL,
`COACH_ID` INT NOT NULL,
`PROCLASSORDER_STATE` CHAR(1),
`PROCLASSORDER_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (`PROCLASSORDER_ID`),
FOREIGN KEY (`PROCLASS_ID`) REFERENCES `PROCLASS` (`PROCLASS_ID`),
FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`),
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`)
);
CREATE TABLE `COACHSCHEDULE` (
`COACHSCHEDULE_ID` INT NOT NULL AUTO_INCREMENT,
`COACH_ID` INT NOT NULL,
`COACHSCHEDULE_DATE` DATE NOT NULL,
`COACHSCHEDULE_TIME` CHAR(1),
`COACHSCHEDULE_TYPE` INT,
`COACHSCHEDULE_CLASSID` INT,
PRIMARY KEY (`COACHSCHEDULE_ID`),
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`)
);
CREATE TABLE `COACHDAYOFF` (
`COACHDAYOFF_ID` INT NOT NULL AUTO_INCREMENT,
`COACH_ID` INT NOT NULL,
`COACHDAYOFF_DATE` DATE NOT NULL,
`COACHDAYOFF_TIME` CHAR(1),
PRIMARY KEY (`COACHDAYOFF_ID`),
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`)
);
-- --創建員工表格-------------------------------------------------
CREATE TABLE `DEPARTMENT` (
`DEPARTMENT_ID` INT NOT NULL AUTO_INCREMENT,
`DEPARTMENT_NAME` VARCHAR(200) NOT NULL,
PRIMARY KEY (`DEPARTMENT_ID`)
);
CREATE TABLE `EMPLOYEE` (
`EMPLOYEE_ID` INT NOT NULL AUTO_INCREMENT,
`DEPARTMENT_ID` INT NOT NULL,
`EMPLOYEE_NAME` VARCHAR(20) NOT NULL,
`EMPLOYEE_MAIL` VARCHAR(200) NOT NULL,
`EMPLOYEE_PASSWORD` VARCHAR(10) NOT NULL,
`EMPLOYEE_STATE` CHAR(5) NOT NULL,
PRIMARY KEY (`EMPLOYEE_ID`),
FOREIGN KEY (`DEPARTMENT_ID`) REFERENCES DEPARTMENT (`DEPARTMENT_ID`)
);
CREATE TABLE `ACCESS` (
`ACCESS_ID` INT NOT NULL AUTO_INCREMENT,
`ACCESS_NAME` VARCHAR(200) NOT NULL,
PRIMARY KEY (`ACCESS_ID`)
);
CREATE TABLE `EMPLOYEE_ACCESS` (
`EMPLOYEEACCESS_ID` INT NOT NULL AUTO_INCREMENT,
`EMPLOYEE_ID` INT NOT NULL,
`ACCESS_ID` INT NOT NULL,
PRIMARY KEY (`EMPLOYEEACCESS_ID`),
FOREIGN KEY (`EMPLOYEE_ID`) REFERENCES `EMPLOYEE` (`EMPLOYEE_ID`),
FOREIGN KEY (`ACCESS_ID`) REFERENCES `ACCESS` (`ACCESS_ID`)
);
-- --創建團課表格-------------------------------------------------

CREATE TABLE `COURSE` (
`COURSE_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`COURSE_CATEGORY` VARCHAR(20) NOT NULL,
`COURSE_NAME` VARCHAR(20) NOT NULL,
`COURSE_INTRODUCTION` VARCHAR(500) NOT NULL,
`COACH_ID` INT NOT NULL,
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`)
);
CREATE TABLE `PERIOD` (
`PERIOD_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`PEOPLE_UPPER` INT NOT NULL,
`PEOPLE_LOWER` INT NOT NULL,
`COURSE_ORDER_BE` TIMESTAMP NOT NULL,
`COURSE_ORDER_EN` TIMESTAMP NOT NULL,
`COURSE_PRICE` INT NOT NULL,
`COURSE_NUMBER` INT NOT NULL,
`COURSE_STATE` VARCHAR(2) Default '上架',
`COURSE_ID` INT NOT NULL,
FOREIGN KEY (`COURSE_ID`) REFERENCES `COURSE` (`COURSE_ID`)
);

CREATE TABLE `COURSE_SCHEDULE`(
`COURSE_SCHEDULE_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`COURSE_SCHEDULE_DATE` DATE NOT NULL,
`COURSE_SCHEDULE_TIME` VARCHAR(1) NOT NULL,
`PERIOD_ID` INT NOT NULL ,
`COACH_ID` INT NOT NULL,
`COURSE_SCHEDULE_STATE` VARCHAR(3) DEFAULT '已成立',
FOREIGN KEY (`PERIOD_ID`) REFERENCES `PERIOD` (`PERIOD_ID`),
FOREIGN KEY (`COACH_ID`) REFERENCES `COACH` (`COACH_ID`)
);
CREATE TABLE `COURSE_SHOWOFF`(
`COURSE_SHOWOFF_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`COURSE_SHOWOFF_DATE` DATE NOT NULL,
`COURSE_SHOWOFF_STATE` CHAR(1) NOT NULL,
`COURSE_SCHEDULE_ID` INT NOT NULL ,
`MEMBER_ID` INT NOT NULL,
FOREIGN KEY (`COURSE_SCHEDULE_ID`) REFERENCES `COURSE_SCHEDULE` (`COURSE_SCHEDULE_ID`),
FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
);

CREATE TABLE `COURSE_ORDER`(
`COURSE_ORDER_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`COURSE_ORDER_DATE` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`COURSE_ORDER_STATE` VARCHAR(3) DEFAULT '已成立',
`COURSE_ORDER_TOTAL_PRICE` INT NOT NULL,
`PERIOD_ID` INT NOT NULL ,
`MEMBER_ID` INT NOT NULL,
FOREIGN KEY (`PERIOD_ID`) REFERENCES `PERIOD` (`PERIOD_ID`),
FOREIGN KEY (`MEMBER_ID`) REFERENCES `MEMBER` (`MEMBER_ID`)
);
-- --創建常見問題表格-------------------------------------------------
CREATE TABLE `FAQS`(
`FAQS_ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
`FAQS_CATEGORY` VARCHAR(20) NOT NULL,
`FAQS_QUESTION` VARCHAR(500) NOT NULL,
`FAQS_ANSWER` VARCHAR(500) NOT NULL,
`FAQS_UPDATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
-- --創建最新消息表格-------------------------------------------------
CREATE TABLE `NEWS` (
`NEWS_ID` INT NOT NULL AUTO_INCREMENT,
`NEWS_IMG` LONGBLOB,
`NEWS_TIME` TIMESTAMP,
PRIMARY KEY (`NEWS_ID`)
);
-- --創建商城表格-------------------------------------------------
CREATE TABLE `CATEGORY` (
`CATEGORY_ID` INT NOT NULL AUTO_INCREMENT,
`CATEGORY_NAME` VARCHAR(45) NOT NULL,
PRIMARY KEY (`CATEGORY_ID`));
CREATE TABLE `PRODUCT` (
`PRODUCT_ID` INT NOT NULL AUTO_INCREMENT,
`PRODUCT_NAME` VARCHAR(100) NOT NULL,
`PRODUCT_PRICE` INT NOT NULL,
`PRODUCT_DETAIL` VARCHAR(500) NOT NULL,
`PRODUCT_STATUS` INT NOT NULL,
`PRODUCT_CATEGORYID` INT NOT NULL,
`PRODUCT_CREATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`PRODUCT_UPDATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (`PRODUCT_ID`),
CONSTRAINT `PRODUCT_CATEGORYID`FOREIGN KEY (`PRODUCT_CATEGORYID`)REFERENCES `CATEGORY` (`CATEGORY_ID`)
);
CREATE TABLE `PRODUCT_IMAGE` (
`PRODUCT_IMAGE_ID` INT NOT NULL AUTO_INCREMENT,
`PRODUCTIMAGE_PRODUCTID` INT NOT NULL,
`PRODUCTIMAGE` BLOB,
PRIMARY KEY (`PRODUCT_IMAGE_ID`),
CONSTRAINT `PRODUCTIMAGE_PRODUCTID` FOREIGN KEY (`PRODUCTIMAGE_PRODUCTID`) REFERENCES `PRODUCT` (`PRODUCT_ID`)
);
CREATE TABLE `SHOPORDER` (
`SHOPORDER_ID` INT NOT NULL AUTO_INCREMENT,
`SHOPORDER_MEMBERID` INT NOT NULL,
`SHOPORDER_CREATETIME` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
`SHOPORDER_TOTALPRICE` INT NOT NULL,
`SHOPORDER_STATUS` INT NOT NULL,
`SHOPORDER_ADDERESS` VARCHAR(100),
`SHOPORDER_NAME` VARCHAR(20),
`SHOPORDER_PHONE` INT,
`SHOPORDER_NOTE` VARCHAR(100),
PRIMARY KEY (`SHOPORDER_ID`),
FOREIGN KEY (`SHOPORDER_MEMBERID`) REFERENCES MEMBER (`MEMBER_ID`)
);
CREATE TABLE `SHOPORDER_DETAIL` (
`SHOPORDER_DETAIL_SHOPORDERID` INT NOT NULL AUTO_INCREMENT,
`SHOPORDER_DETAIL_PRODUCTID` INT NOT NULL,
`SHOPORDER_DETAIL_QUANTITY` INT,
`SHOPORDER_DETAIL_PRICE` INT,
PRIMARY KEY (`SHOPORDER_DETAIL_SHOPORDERID`, `SHOPORDER_DETAIL_PRODUCTID`),
FOREIGN KEY (`SHOPORDER_DETAIL_SHOPORDERID`) REFERENCES `SHOPORDER` (`SHOPORDER_ID`),
FOREIGN KEY (`SHOPORDER_DETAIL_PRODUCTID`) REFERENCES `PRODUCT` (`PRODUCT_ID`)
);